version: '2.1'

services:
  mysql:
    image: mysql:5.7.32
    mem_limit: 512m
    ports:
      - "3313:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=stock-level-db
      - MYSQL_USER=test
      - MYSQL_PASSWORD=pwd
    healthcheck:
      test: "/usr/bin/mysql --user=test --password=pwd --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 2s
      retries: 60
    
  stock-level:
    build: .
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dockerlocal
    depends_on:
      mysql:
        condition: service_healthy